### ISSUE TITLE
App fails to deploy using toolchain

### ISSUE THREAD

**Issue by timroster** [IBM/Industrial-Visual-Analysis#13]
The Watson Visual Recognition service has changed plan name from free to lite, which breaks the declared services in `manifest.yml`

**Comment by philippe-gregoire** [comment]
So, actually what happens is that the VR service has been moved to being an ibmcloud resource and no more an cf service. In order to bind it to a CF app, an alias needs to be created:
```
ibmcloud resource service-alias-create "Visual Recognition-cfc" --instance-name "Visual Recognition-cfc" -s Dev
```

**Comment by raheelzubairy** [comment]
Thanks @timroster @philippe-gregoire 
That command worked to create a CF alias service. Updated readme with PR #15  

<img width="818" alt="screen shot 2018-06-21 at 5 46 18 pm" src="https://user-images.githubusercontent.com/27243319/41749662-581a787e-757d-11e8-80a1-17adb445f89f.png">
