### ISSUE TITLE
setup_functions.sh does not have update function

### ISSUE THREAD

**Issue by kyokonishito** [IBM/Industrial-Visual-Analysis#19]
setup_functions.sh does not have update function. Therefore --update option causes following error.

```
Analysis:$ ./setup_functions.sh --update
Current namespace is _.
./setup_functions.sh: line 129: update: command not found
```

Could you add update function or remove the description about update from README.md?

Thank you.

**Comment by raheelzubairy** [comment]
@kyokonishito  Yes, there is no update function in the script.  Thanks for the feedback. 
Have corrected here: #21
